/*==========================================================*
    *  Creacion de la base de datos restaurante             *
    *  Creado por: Angela Camila Montenegro Granados        *
                   Germán Esteban Rodriguez Garcia          *
                   Cristian Camilo Roncancio Peña           *
                   Cristhian Fernando Moreno Manrique       *
    *  Fecha: 12 - Octubre - 2025                           *
*==========================================================*/

drop user restaurante cascade;
create user restaurante identified by a;
grant connect,resource to restaurante;
alter user restaurante
   quota unlimited on users;
CONN RESTAURANTE/A

-- ENTIDAD VENTAS --
create table ventas (
   id_venta    number(10) generated by default as identity,
   fecha_venta date not null default sysdate,
   constraint pk_id_ventas primary key ( id_venta )
);

--ENTIDAD PLATOS --
create table platos (
   id_plato    number(10) generated by default as identity,
   tipo_plato  varchar2(50) not null,
   nombre      varchar2(200) not null,
   descripcion varchar2(100) not null,
   constraint pk_id_plato primary key ( id_plato )
);
/*==============================================================*/
/* Table: MENUS                                                 */
/*==============================================================*/
create table menus (
   id_menu          number(10) generated by default on null as identity ( start with 1 increment by 1 minvalue 1 maxvalue 9999999999
   nocache ),
   descripcion_menu varchar2(100) not null,
   constraint pk_menus primary key ( id_menu )
);
/*==============================================================*/
/* Table: VENTAS_MENUS                                                 */
/*==============================================================*/
create table ventas_menus (
   id_ventas_menu number(10) generated by default on null as identity ( start with 1 increment by 1 minvalue 1 maxvalue 9999999999
   nocache ),
   id_menu        number(10) not null,
   id_ventas      number(10) not null,
   cantidad       number(10) not null,
   constraint ventas_menus primary key ( id_ventas_menu )
);