/*==========================================================*
    *  Creacion de la base de datos restaurante             *
    *  Creado por: Angela Camila Montenegro Granados        *
                   Germán Esteban Rodriguez Garcia          *
                   Cristian Camilo Roncancio Peña           *
                   Cristhian Fernando Moreno Manrique       *
    *  Fecha: 12 - Octubre - 2025                           *
*==========================================================*/

DROP USER RESTAURANTE CASCADE;
CREATE USER RESTAURANTE IDENTIFIED BY A;
GRANT CONNECT, RESOURCE TO RESTAURANTE;
ALTER USER RESTAURANTE QUOTA UNLIMITED ON USERS;
CONN RESTAURANTE/A

-- ENTIDAD VENTAS --
CREATE TABLE VENTAS (
    ID_VENTA NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    FECHA_VENTA DATE    NOT NULL DEFAULT SYSDATE,
    CONSTRAINT PK_ID_VENTAS PRIMARY KEY (ID_VENTA)
);

--ENTIDAD PLATOS --
CREATE TABLE PLATOS (
    ID_PLATO    NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
    TIPO_PLATO  VARCHAR2(50)  NOT NULL,
    NOMBRE      VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ID_PLATO PRIMARY KEY (ID_PLATO)
);

-- ENTIDAD MENUS
create table MENUS
(
    ID_MENU              NUMBER(10)GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCACHE),
    DESCRIPCION_MENU     VARCHAR2(100)              not null,
    constraint PK_MENUS primary key (ID_MENU)
);

-- PLATOS_MENU (relación N:M entre PLATOS y MENUS)
CREATE TABLE PLATOS_MENU (
    ID_MENU NUMBER(10) NOT NULL,
    ID_PLATO NUMBER(10) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    FECHA DATE,
    CONSTRAINT pk_platos_menu PRIMARY KEY (ID_MENU, ID_PLATO),
    CONSTRAINT fk_platos_menu_menu FOREIGN KEY (ID_MENU)
        REFERENCES MENUS(ID_MENU),
    CONSTRAINT fk_platos_menu_plato FOREIGN KEY (ID_PLATO)
        REFERENCES PLATOS(ID_PLATO)
);

-- ENTIDAD VENTAS_MENU 
create table ventas_menus (
   id_ventas_menu number(10) generated by default on null as identity ( start with 1 increment by 1 minvalue 1 maxvalue 9999999999
   nocache ),
   id_menu        number(10) not null,
   id_ventas      number(10) not null,
   cantidad       number(10) not null,
   constraint ventas_menus primary key ( id_ventas_menu ),
   constraint fk_ventas_menu_ventas foreign key (id_venta)
      references ventas(id_venta),
   constraint fk_ventas_menu_menu foreign key (id_menu)
      references menus(id_menu)
);
