/*==============================================================*/
/* Table: MENUS                                                 */
/*==============================================================*/
create table MENUS
(
    ID_MENU              NUMBER(10)GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 NOCACHE)
    DESCRIPCION_MENU     VARCHAR2(100)              not null,
    constraint PK_MENUS primary key (ID_MENU)
);
